### PR TITLE
fix: pass all props to cardItem and CardList

### LINKED ISSUE #264: The justify prop on CardList.Item is not working
### What version of Design System are you using?

0.15.1-pr--51a4b2d

### Steps to Reproduce

Try to pass the justify prop to the CardList.Item component.

### Expected Behavior

The justify prop should be able to spread or center the items in the CardList.Item. 

### Actual Behavior

The items in the CardList.Item do not move.  I think this has something to do with the internal Flex in the CardList.Item component.

### PR DESCRIPTION
**Pull request by tomiiide**
closes #264

### CODE REVIEW

File: design-system/react/src/components/CardList/CardList.tsx [hunk 1]
```diff
@@ -8,13 +10,15 @@ import { CardListContext } from './defs';
...
 import { Components } from '~/defs';
-import { useElementProps, useStyles } from '~/hooks';
+import { useStyles } from '~/hooks';
 
 export const CardList = _unstable_createComponent<t.CardListDef>(
   Components.CardList,
   ({ children, gap = '$2', isClickable, autoFocus, ...props }) => {
     const classes = useStyles(styles, props, ['root']);
-    const elementProps = useElementProps(props, classes.root);
+    const elementProps = mergeProps(props, {
```
Comment (matt-user) [inline design-system/react/src/components/CardList/CardList.tsx:19]:
```suggestion
    const mergeProps = mergeProps(props, {
```

File: design-system/react/src/components/CardList/CardListItem.tsx [hunk 2]
```diff
@@ -7,14 +9,16 @@ import { useCardListContext } from './defs';
...
-import { useElementProps, useStyles } from '~/hooks';
+import { useStyles } from '~/hooks';
 
 export const CardListItem = _unstable_createComponent<CardListItemDef>(
   Components.CardListItem,
   ({ children, rightEl, isActive, ...props }) => {
     const { isClickable } = useCardListContext();
     const classes = useStyles(styles, props, ['item']);
-    const elementProps = useElementProps(props, classes.item);
+    const elementProps = mergeProps(props, {
```
Comment (matt-user) [inline design-system/react/src/components/CardList/CardListItem.tsx:19]:
```suggestion
    const mergeProps = mergeProps(props, {
```

**Review by matt-user — CHANGES_REQUESTED** [review]

**Review by matt-user — APPROVED** [review]
